# Language support configuration.
# See the languages documentation: https://docs.helix-editor.com/master/languages.html

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript", "--printWidith", "100"] }
auto-format = true
