set -g status-keys vi
set -sg escape-time 0
setw -g mode-keys vi

# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# smart pane switching with awareness of vim splits
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# show yellow border around active pane
set-option -g pane-active-border-style bg=yellow

# show pane numbers until one is selected
bind -T prefix q display-panes -d 0

set -g default-shell /usr/bin/zsh
