# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
# set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

set -g default-terminal "screen-256color"

set -g status-keys vi
set -sg escape-time 5
setw -g mode-keys vi

# Resize Pane
bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R

# Select panes
unbind Up
unbind Down
unbind Left
unbind Right
bind C-k select-pane -U
bind C-j select-pane -D
bind C-l select-pane -R
bind C-h select-pane -L

# show yellow border around active pane
set-option -g pane-active-border-style bg=yellow

# show pane numbers until one is selected
bind -T prefix q display-panes -d 0

set-option -g default-shell $SHELL

# Plugins
set -g @plugin "tmux-plugins/tpm"

set -g @plugin "jimeh/tmux-themepack"
set -g @themepack "powerline/default/cyan"

run "~/.tmux/plugins/tpm/tpm"

