set rtp+=$HOME/.vim/bundle/Vundle.vim/
call vundle#begin('$HOME/.vim/bundle/')

" Plugins
call vundle#begin()
	Plugin 'VundleVim/Vundle.vim'
	Plugin 'ctrlp.vim'
	Plugin 'Gundo'
	Plugin 'Lokaltog/vim-powerline'
	Plugin 'ragtag.vim'
	Plugin 'scrooloose/nerdtree'
	Plugin 'scrooloose/nerdcommenter'
	Plugin 'scrooloose/syntastic'
	Plugin 'surround.vim'
	Plugin 'YankRing.vim'
	Plugin 'Valloric/YouCompleteMe' 
	Plugin 'mattn/emmet-vim'
	Plugin 'tpope/vim-commentary'
	Plugin 'tpope/vim-fugitive'
	Plugin 'fatih/vim-go'
	Plugin 'majutsushi/tagbar'
	Plugin 'tomasr/molokai'
	Plugin 'editorconfig/editorconfig-vim'
	Plugin 'sirver/ultisnips'
	Plugin 'honza/vim-snippets'
	Plugin 'itchyny/lightline.vim'
	Plugin 'ElmCast/elm-vim'
	Plugin 'mhinz/vim-startify'
	Plugin 'airblade/vim-gitgutter'
	Plugin 'junegunn/fzf'
	" Plugin 'w0rp/ale'
call vundle#end()

set encoding=utf-8

" use indentation plugins => .vim/after/ftplugin 
filetype plugin indent on

" Leader
let mapleader = ","

set backspace=2		" Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile		" http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler           " show the cursor position all the time
set showcmd         " display incomplete commands
set incsearch       " do incremental searching
set laststatus=2    " Always display the status line
set autowrite       " Automatically :write before running commands
set autoread        " Auto reload files when changed
set hidden			" allow new buffers to be opened without saving the current
set nowrap			" don't wrap lines, keep em' short!
set autochdir		" set the cwd to the current file
set guioptions-=m	" Remove menu bar
set guioptions-=T	" Remove toolbar, left scrollbar and right scrollbar
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
set splitbelow		" Open new split panes to right and bottom, which feels more natural
set splitright
set tabstop=4		" Default widths.  See ftplugin paths for language specific settings
set shiftwidth=4
set softtabstop=4
set colorcolumn=80	" Color cols
set number
	
" Ctrl-p
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_custom_ignore = 'elm-stuff\|node_modules\|DS_Store\|git\|vendor\|tmp'
map <C-p> :CtrlP<CR>
map <A-p> :CtrlPBuffer<cr>
" map <S-p>m :CtrlPMRU<cr>

:imap jj <Esc>

" Go
" map <c-g><c-d> :GoDef<CR>
" map <c-g><c-i> :GoDoc<CR>
" let g:go_bin_path = "C:\Users\Chris\Go" 

" UltiSnips
let g:UltiSnipsSnippetDirectories=[$HOME . "/vim-snippets"]
" let g:UltiSnipsExpandTrigger="<tab>"
" let g:UltiSnipsJumpForwardTrigger="<c->"
" let g:UltiSnipsJumpBackwardTrigger="<c-k>"
" let g:UltiSnipsExpandTrigger = "<nop>"
" let g:ulti_expand_or_jump_res = 0
" function ExpandSnippetOrCarriageReturn()
"     let snippet = UltiSnips#ExpandSnippetOrJump()
"     if g:ulti_expand_or_jump_res > 0
"         return snippet
"     else
"         return "\<CR>"
"     endif
" endfunction
" inoremap <expr> <CR> pumvisible() ? "<C-R>=ExpandSnippetOrCarriageReturn()<CR>" : "\<CR>"

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"


" NerdTree 
nmap <c-n> :NERDTreeToggle<cr>

syntax on 
" set noautoindent
" set nocindent
" set nosmartindent

" Color scheme
colorscheme molokai 
" highlight Normal guibg=#131313
" highlight Folded guibg=#0A0A0A guifg=#9090D0

" Font
set guifont=Droid\ Sans\ Mono:h10 linespace=0

" Quickly get out of insert mode without your fingers having to leave the
" home row (either use 'jj' or 'jk')
inoremap jj <Esc>

" File Settings
autocmd FileType unix,css,scss,yaml,html,javascript,py,go autocmd BufWritePre <buffer> :%s/\s\+$//e
" autocmd FileType html setlocal shiftwidth=4 tabstop=4 expandtab
" autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4

" Ignores
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

" Syntastic
set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0


" FZF
" map <C-p> :FZF<CR>
" Mapping selecting mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)

" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file-ag)
imap <c-x><c-l> <plug>(fzf-complete-line)

" Advanced customization using autoload functions
inoremap <expr> <c-x><c-k> fzf#vim#complete#word({'left': '15%'})
