" Vundle requirements
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'closetag.vim'
Bundle 'ctrlp.vim'
Bundle 'dhruvasagar/vim-railscasts-theme'
Bundle 'Gundo'
Bundle 'Lokaltog/vim-powerline'
Bundle 'https://github.com/digitaltoad/vim-jade'
Bundle 'ragtag.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'surround.vim'
Bundle 'UltiSnips'
Bundle 'YankRing.vim'
Bundle 'https://github.com/Valloric/YouCompleteMe'
Bundle 'https://github.com/honza/vim-snippets'
Bundle 'https://github.com/mattn/emmet-vim'
" Bundle 'https://github.com/wookiehangover/jshint.vim'

filetype plugin indent on

" Leader
let mapleader = ","

set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands

" Default widths.  See ftplugin paths for language specific settings
set tabstop=2
set shiftwidth=2
set expandtab

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Emmet key remapping
let g:user_emmet_leader_key='<C-E>'

" Remap ctrl-p
let g:ctrlp_map = '<F11>'
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'
map <leader>t :CtrlP<CR>
map <leader>b :CtrlPBuffer<cr>
map <leader>m :CtrlPMRU<cr>

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-space>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" My shortcuts
nmap <F1> :NERDTree<cr>
nmap <F2> :NERDTreeClose<cr>

syntax on
" set noautoindent
" set nocindent
" set nosmartindent


" allow new buffers to be opened without saving the current
set hidden

" don't wrap lines
" set nowrap
set wrap

" set the cwd to the current file
" cool but messes up some rails commands that need to be run from the root
" set autochdir

" Color scheme
colorscheme railscasts
highlight Normal guibg=#131313
highlight Folded guibg=#0A0A0A guifg=#9090D0

" Set font
set guifont=Inconsolata\ 10 linespace=0

" Remove menu bar
set guioptions-=m

" Remove toolbar, left scrollbar and right scrollbar
set guioptions-=T
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" Folding
" nnoremap <Space> za
" vnoremap <Space> za
set nofoldenable  " turn off folding

" Yank/paste to the OS clipboard with ,y and ,p
nnoremap <leader>y "+y
nnoremap <leader>p "+p
nnoremap <leader>Y "+yy
nnoremap <leader>P "+P

" Quickly get out of insert mode without your fingers having to leave the
" home row (either use 'jj' or 'jk')
inoremap jj <Esc>

" Remap j and k to act as expected when used on long, wrapped, lines
nnoremap j gj
nnoremap k gk

" Run Ack fast
nnoremap <leader>a :Ack<Space>

" Treat <li> and <p> tags like the block tags they are
let g:html_indent_tags = 'li\|p'

" We don't need no stinking whitespace
autocmd FileType jade,unix,coffee,css,cucumber,haml,ruby,sass,scss,yaml,html,javascript,less,py autocmd BufWritePre <buffer> :%s/\s\+$//e
