" Vundle requirements
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'closetag.vim'
Bundle 'ctrlp.vim'
Bundle 'Gundo'
Bundle 'Lokaltog/vim-powerline'
Bundle 'ragtag.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'surround.vim'
Bundle 'UltiSnips'
Bundle 'YankRing.vim'
Bundle 'editorconfig/editorconfig-vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'honza/vim-snippets'
Bundle 'mattn/emmet-vim'
Bundle '907th/vim-auto-save'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-fugitive'
Bundle 'rking/ag.vim'
Bundle 'Shutnik/jshint2.vim'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'jiangmiao/auto-pairs'
Bundle 'vim-scripts/JavaScript-Indent'
Bundle 'groenewege/vim-less'
Bundle 'fatih/vim-go'
Bundle 'majutsushi/tagbar'
Bundle 'mustache/vim-mustache-handlebars'
Bundle 'ap/vim-css-color'

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
Bundle 'junegunn/vim-easy-align'
vmap <Enter> <Plug>(EasyAlign)

filetype plugin on
filetype plugin indent on

" Go
let g:go_disable_autoinstall = 0

" Leader
let mapleader = ","

set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands
set autoread      " Auto reload files when changed

" Default widths.  See ftplugin paths for language specific settings
set tabstop=2
set shiftwidth=2
set expandtab

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" " AutoSave
let g:auto_save = 0
let jshint2_save = 1

" GSnips
let g:snips_author_email='olsen.chris@gmail.com'
let g:snips_author='Chris Olsen'

" Emmet key remapping
let g:user_emmet_leader_key='<C-E>'

" Remap ctrl-p => <,-t>
let g:ctrlp_map = '<F11>'
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|vendor\|tmp'
map <leader>t :CtrlP<CR>
map <leader>b :CtrlPBuffer<cr>
map <leader>m :CtrlPMRU<cr>

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-space>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" My shortcuts
nmap <F1> :NERDTree<cr>
nmap <F2> :NERDTreeClose<cr>

syntax on 
" set noautoindent
" set nocindent
" set nosmartindent


" allow new buffers to be opened without saving the current
set hidden

" don't wrap lines, keep em' short!
set nowrap

" set the cwd to the current file
set autochdir

" Color scheme
colorscheme molokai 
highlight Normal guibg=#131313
highlight Folded guibg=#0A0A0A guifg=#9090D0

" Set font
if has("unix")
  let s:uname = system("uname -s")
  if s:uname == "Darwin"
    set guifont=Inconsolata:h18
  elseif s:uname == "Linux"
    set guifont=Inconsolata\ 12 linespace=0
  endif
endif

" Remove menu bar
set guioptions-=m

" Remove toolbar, left scrollbar and right scrollbar
set guioptions-=T
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" Folding
" nnoremap <Space> za
" vnoremap <Space> za
set foldlevelstart=999
set foldlevel=999
" set foldmethod=indent
set nofoldenable  " turn off folding      
let g:DisableAutoJavascriptFolding = 1
let g:DisableAutoCssFolding = 1

" Yank/paste to the OS clipboard with ,y and ,p
" au FileType javascript call JavaScriptFold()

nnoremap <leader>y "+y
nnoremap <leader>p "+p
nnoremap <leader>Y "+yy
nnoremap <leader>P "+P

" Quickly get out of insert mode without your fingers having to leave the
" home row (either use 'jj' or 'jk')
inoremap jj <Esc>

" Remap j and k to act as expected when used on long, wrapped, lines
nnoremap j gj
nnoremap k gk

" Run Ack fast
nnoremap <leader>a :Ack<Space>

" Color cols
set colorcolumn=80

" https://github.com/ggreer/the_silver_searcher
let g:ackprg = 'ag --nogroup --nocolor --column'  

" Treat <li> and <p> tags like the block tags they are
let g:html_indent_tags = 'li\|p'

" Quick search and replace
:nnoremap <Leader>s :%s/\<<C-r><C-w>\>/

" TODOS / FIXME
" command Todo noautocmd vimgrep /TODO\|FIXME/j ** | cw
" let g:winManagerWindowLayout = 'TodoList,FileExplorer|BufExplorer' 

" Disable auto syntax check for go
let g:go_fmt_fail_silently = 1

" We don't need no stinking whitespace
autocmd FileType jade,unix,coffee,css,cucumber,haml,ruby,sass,scss,yaml,html,javascript,less,py,go,hbs autocmd BufWritePre <buffer> :%s/\s\+$//e

" show/hide the tagbar
nmap <F8> :TagbarToggle<CR>

" Go highlighting
let g:tagbar_type_go = {  
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : 'gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }

